app:
  wa-api-key: ${APP_WA_API_KEY}
  execution:
    max-retry-attempts: ${APP_EXEC_MAX_RETRIES:3}
    database:
      poll: ${APP_DB_POLL:true}
      initial-delay: ${APP_DB_POLL_INITIAL_DELAY:5s}
      no-job-delay: ${APP_DB_POLL_NO_JOB_DELAY:60s}
    amqp:
      exchange: ${APP_AMQP_EXCHANGE:whales}
      routing-key: ${APP_AMQP_ROUTING_KEY:alert.new}

spring:
  main:
    banner-mode: off

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}

  rabbitmq:
    host: ${AMQP_HOST:localhost}
    port: ${AMQP_PORT:5672}
    username: ${AMQP_USER:guest}
    password: ${AMQP_PASS:guest}
    virtual-host: ${AMQP_VHOST:/}
